# Site settings
title: Debian Quickstart
tag_text: Debian Quickstart
description: Sane defaults for the twenty-first century.

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ["README.md"]
sass:
  style: compressed
